-- MySQL Script generated by MySQL Workbench
-- Sun Jan 17 01:02:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `Usuarioscol_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Triagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Triagem` (
  `escolaridade` VARCHAR(45) NOT NULL,
  `foco` ENUM('Carreira', 'Estudo', 'Nenhum') NOT NULL,
  `triagemcol` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`Usuarios_idUsuarios`),
  CONSTRAINT `fk_triagem_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `faculdade` ENUM('Nao', 'Sim') NOT NULL,
  `tecnico` ENUM('Nao', 'Sim') NOT NULL,
  `profissionalizante` ENUM('Nao', 'Sim') NOT NULL,
  `Triagem_Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`Triagem_Usuarios_idUsuarios`),
  CONSTRAINT `fk_Curso_Triagem1`
    FOREIGN KEY (`Triagem_Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Triagem` (`Usuarios_idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dificuldades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dificuldades` (
  `carreira` ENUM('Nao', 'Sim') NOT NULL,
  `conhecimento` ENUM('Nao', 'Sim') NOT NULL,
  `comportamento` ENUM('Nao', 'Sim') NOT NULL,
  `culturaConexao` ENUM('Nao', 'Sim') NOT NULL,
  `Triagem_Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`Triagem_Usuarios_idUsuarios`),
  CONSTRAINT `fk_Dificuldades_Triagem1`
    FOREIGN KEY (`Triagem_Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Triagem` (`Usuarios_idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
