-- MySQL Script generated by MySQL Workbench
-- Sun Jan 17 09:46:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mentoraqui
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mentoraqui
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mentoraqui` DEFAULT CHARACTER SET utf8 ;
USE `mentoraqui` ;

-- -----------------------------------------------------
-- Table `mentoraqui`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentoraqui`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `categoria` ENUM('Mentorado', 'Mentor') NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mentoraqui`.`Triagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentoraqui`.`Triagem` (
  `escolaridade` VARCHAR(45) NOT NULL,
  `foco` ENUM('Carreira', 'Estudo', 'Nenhum') NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
#  PRIMARY KEY (`Usuario_idUsuario`),
  CONSTRAINT `fk_Triagem_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mentoraqui`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mentoraqui`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentoraqui`.`Curso` (
  `faculdade` ENUM('Nao', 'Sim') NOT NULL,
  `tecnico` ENUM('Nao', 'Sim') NOT NULL,
  `profissionalizante` ENUM('Nao', 'Sim') NOT NULL,
  `Triagem_Usuario_idUsuario` INT NOT NULL,
#  PRIMARY KEY (`Triagem_Usuario_idUsuario`),
  CONSTRAINT `fk_Curso_Triagem1`
    FOREIGN KEY (`Triagem_Usuario_idUsuario`)
    REFERENCES `mentoraqui`.`Triagem` (`Usuario_idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mentoraqui`.`Dificuldades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentoraqui`.`Dificuldades` (
  `carreira` ENUM('Nao', 'Sim') NOT NULL,
  `conhecimento` ENUM('Nao', 'Sim') NOT NULL,
  `comportamento` ENUM('Nao', 'Sim') NOT NULL,
  `culturaConexao` ENUM('Nao', 'Sim') NOT NULL,
  `Triagem_Usuario_idUsuario` INT NOT NULL,
#  PRIMARY KEY (`Triagem_Usuario_idUsuario`),
  CONSTRAINT `fk_Dificuldades_Triagem1`
    FOREIGN KEY (`Triagem_Usuario_idUsuario`)
    REFERENCES `mentoraqui`.`Triagem` (`Usuario_idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mentoraqui`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentoraqui`.`Match` (
  `idMentor` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
#  PRIMARY KEY (`Usuario_idUsuario`),
  CONSTRAINT `fk_Match_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mentoraqui`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
